version: "3"
services:
  go-app:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    network_mode: host
    #ports:
    #  - "8080:8081"
    environment:
      - GOMAXPROCS=4
    deploy:
      mode: replicated
      replicas: 4
