version: "3"
services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./html:/usr/share/nginx/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/app

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    restart: always
    ports: ["8081:80"]
    depends_on: ["php"]

  composer:
    image: composer
    volumes:
      - ./app:/app
    links:
      - php
    command: "composer update"
